feat: add vector layer to mapbox
urbanSpatial/LetsPlanOrg pull request #6
Opened 2021-03-03 19:37 UTC by markkimsal

2021-03-11 14:19 UTC, themightychris requested changes

2021-03-11 14:19 UTC, themightychris commented on resources/js/Shared/MapboxMap.vue
> +      });
@markkimsal this code is a big blob of red in the project's existing eslint config. I'm opening another PR to tighten up the config

Ensure that your editor is configured to apply the project's eslint configuration while you work, like seen here in vscode:

![image](https://user-images.githubusercontent.com/458494/110800997-c937cc00-824a-11eb-8877-cd5f9c099ef4.png)

2021-03-11 14:20 UTC, themightychris commented on app/Http/Controllers/TileLayer.php
> +      $hdrs = [
**nitpick**: avoid abbreviations as a general rule on Jarvus projects

2021-03-16 20:02 UTC, markkimsal commented
The files that are failing php lint are not in this branch, I can't fix them.

2021-03-16 21:58 UTC, themightychris commented
@markkimsal the lint errors all appear to be from the changes merged in #7. Ideally, we should have merged the linting PR first, then rebased and cleaned up that one before merging. Since it's already merged, we'll just need another PR now that re-cleans `main`, and then rebase this one on top again after this merges

2021-03-16 22:08 UTC, themightychris commented
@markkimsal I fixed up the formatting of #7  in #8 and then rebased this branch onto the latest `main`, looks good now :+1:

2021-03-18 16:40 UTC, merged